import React, { useEffect, useState } from 'react';
import { useParams, Link } from 'react-router-dom';
import { SEO } from '@/components/SEO';
import { PageHero } from '@/components/PageHero';
import { Calendar, User, Clock, ChevronRight, Facebook, Linkedin, Twitter, Share2 } from 'lucide-react';
import { blogService, BlogPost } from '@/services/blogService';
import { toast } from 'sonner';

const defaultBlog: BlogPost = {
    id: "mock",
    title: "SAS Certification Course in Canada (North America)",
    slug: "sas-certification-course-in-canada-north-america",
    excerpt: "Explore the opportunities of SAS certification in the North American market and how it can boost your data career.",
    content: "<p>This is a <strong>mock content</strong> block displaying because the backend failed to return valid data. Here you would normally see the fully rendered HTML generated by the Rich Text Editor.</p><p><br/></p><h2>Why SAS Certification?</h2><p>SAS helps you achieve business goals...</p><ul><li>Data Analytics</li><li>Cloud Architecture</li><li>AI models</li></ul>",
    author_name: "Admin User",
    created_at: "2025-12-12",
    category: "SAS",
    tags: "certification, sas, career",
    status: "Published",
    image_url: "https://images.unsplash.com/photo-1551836022-d5d88e9218df?q=80&w=600&auto=format&fit=crop"
};

export default function BlogDetail() {
    const { slug } = useParams<{ slug: string }>();
    const [blog, setBlog] = useState<BlogPost | null>(null);
    const [loading, setLoading] = useState(true);

    useEffect(() => {
        fetchBlog();
    }, [slug]);

    const fetchBlog = async () => {
        try {
            setLoading(true);
            const data = await blogService.getBlogBySlug(slug!);
            setBlog(data);
        } catch (error) {
            console.error("Failed to fetch blog details", error);
            toast.error("Loaded Mock data (Backend disconnected or failed)");
            setBlog(defaultBlog);
        } finally {
            setLoading(false);
        }
    };

    const shareUrl = window.location.href;

    if (loading) {
        return (
            <div className="min-h-screen font-sans bg-white pb-24 text-center mt-32 text-gray-500">
                Loading Blog...
            </div>
        );
    }

    if (!blog) {
        return (
            <div className="min-h-screen font-sans bg-white pb-24 text-center mt-32 text-gray-500">
                Blog not found.
            </div>
        );
    }

    return (
        <div className="min-h-screen font-sans bg-white pb-24">
            <SEO
                title={`${blog.title} - NxGen Tech Academy`}
                description={blog.excerpt}
                type="article"
                path={`/blogs/${blog.slug || blog.id}`}
            />

            <PageHero
                title={blog.title}
                description={blog.category}
            >
                <div className="text-sm opacity-90 font-medium flex gap-2 items-center text-white flex-wrap">
                    <Link to="/" className="hover:text-gray-200 transition-colors">Home</Link>
                    <ChevronRight className="w-4 h-4" />
                    <Link to="/blogs" className="hover:text-gray-200 transition-colors">Blogs</Link>
                    <ChevronRight className="w-4 h-4" />
                    <span className="truncate max-w-[200px] md:max-w-md">{blog.title}</span>
                </div>
            </PageHero>

            <div className="container mx-auto px-4 mt-12 max-w-4xl">
                {/* Meta Info */}
                <div className="flex flex-wrap items-center gap-6 text-sm text-slate-500 mb-8 border-b border-slate-100 pb-6">
                    <div className="flex items-center gap-2">
                        <User className="h-5 w-5 text-[#000080]" />
                        <span className="font-semibold text-slate-800">{blog.author_name || "Admin"}</span>
                    </div>
                    <div className="flex items-center gap-2">
                        <Calendar className="h-5 w-5 text-[#000080]" />
                        <span>{blog.created_at ? new Date(blog.created_at).toLocaleDateString() : 'Unknown Date'}</span>
                    </div>
                    <div className="flex items-center gap-2">
                        <Clock className="h-5 w-5 text-[#000080]" />
                        <span>5 min read</span>
                    </div>
                </div>

                {/* Featured Media */}
                {blog.video_url ? (
                    <div className="w-full aspect-video rounded-2xl overflow-hidden mb-12 shadow-lg">
                        <iframe
                            width="100%"
                            height="100%"
                            src={blog.video_url.replace("watch?v=", "embed/")}
                            title={blog.title}
                            frameBorder="0"
                            allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture"
                            allowFullScreen>
                        </iframe>
                    </div>
                ) : blog.image_url ? (
                    <div className="w-full aspect-video rounded-2xl overflow-hidden mb-12 shadow-lg bg-slate-100">
                        <img src={blog.image_url} alt={blog.title} className="w-full h-full object-cover" />
                    </div>
                ) : null}

                {/* Blog Content */}
                <article
                    className="prose prose-lg prose-indigo max-w-none mb-16 text-slate-700 leading-relaxed quill-content border-b pb-12"
                    dangerouslySetInnerHTML={{ __html: blog.content }}
                />

                {/* Tags & Sharing */}
                <div className="flex flex-col md:flex-row justify-between items-center gap-6 py-8">
                    <div className="flex flex-wrap gap-2 items-center">
                        <span className="font-semibold text-slate-800 mr-2">Tags:</span>
                        {blog.tags?.split(',').map((tag, idx) => (
                            <span key={idx} className="bg-slate-100 text-slate-600 px-3 py-1 rounded-full text-sm hover:bg-slate-200 transition-colors cursor-pointer">
                                #{tag.trim()}
                            </span>
                        ))}
                    </div>

                    <div className="flex items-center gap-4">
                        <span className="font-semibold text-slate-800 flex items-center gap-2">
                            <Share2 className="w-4 h-4" /> Share:
                        </span>
                        <a href={`https://www.linkedin.com/sharing/share-offsite/?url=${encodeURIComponent(shareUrl)}`} target="_blank" rel="noreferrer" className="w-10 h-10 rounded-full bg-[#0077b5] text-white flex items-center justify-center hover:bg-[#0077b5]/90 transition-colors shadow-sm cursor-pointer border border-[#0077b5]">
                            <Linkedin className="w-5 h-5 fill-current" />
                        </a>
                        <a href={`https://www.facebook.com/sharer/sharer.php?u=${encodeURIComponent(shareUrl)}`} target="_blank" rel="noreferrer" className="w-10 h-10 rounded-full bg-[#1877f2] text-white flex items-center justify-center hover:bg-[#1877f2]/90 transition-colors shadow-sm cursor-pointer border border-[#1877f2]">
                            <Facebook className="w-5 h-5 fill-current" />
                        </a>
                        <a href={`https://twitter.com/intent/tweet?url=${encodeURIComponent(shareUrl)}&title=${encodeURIComponent(blog.title)}`} target="_blank" rel="noreferrer" className="w-10 h-10 rounded-full bg-[#1da1f2] text-white flex items-center justify-center hover:bg-[#1da1f2]/90 transition-colors shadow-sm cursor-pointer border border-[#1da1f2]">
                            <Twitter className="w-5 h-5 fill-current" />
                        </a>
                        <a href={`https://api.whatsapp.com/send?text=${encodeURIComponent(blog.title + " " + shareUrl)}`} target="_blank" rel="noreferrer" className="w-10 h-10 rounded-full bg-[#25d366] text-white flex items-center justify-center hover:bg-[#25d366]/90 transition-colors shadow-sm cursor-pointer border border-[#25d366]">
                            <span className="font-bold text-lg leading-none mt-[2px]">W</span>
                        </a>
                    </div>
                </div>

            </div>
        </div>
    );
}
